### ISSUE TITLE
Fitting a mixed-effect model --> dream() instead of lmFit() or duplicateCorrelation()?

### ISSUE THREAD

**Issue by aidarripoll** [phipsonlab/speckle_old#4]
Hi,

Thanks for the clear explanations of your [vignette](https://rdrr.io/github/Oshlack/speckle/f/vignettes/speckle.Rmd)!

I am interested in fitting a mixed-effect model (i.e., including the sequencing lane as a random effect). I noticed that in the **'More complex (or just different) experimental designs'** section, you suggest to use `lmFit()` for LM, or `duplicateCorrelation()` for LMM, but I was wondering whether I could use `dream()` on the transformed proportions (`props$TransformedProps` of the vignette) since `dream()` can hold mixed-models and `lmFit()` not. See section[ 'Dream Analysis'](https://www.bioconductor.org/packages/devel/bioc/vignettes/variancePartition/inst/doc/dream.html) for more details.  

Thanks a lot!

Best,
Aida

**Comment by bphipson** [comment]
Hi Aida

Thanks for using propeller! I have never used dream() before, but from the details from the link above I think it would be fine to use the transformed proportions and put them directly into dream(). You would not run the voomWithDreamWeights step because we deal with the mean-var relationship when we transform the proportions. As long as dream() can take a matrix as input it should work out fine. I would be interested to know if it works for you.

Cheers,
Belinda

**Comment by aidarripoll** [comment]
I have tried it and it seems `dream()` can take as the 'exprObj' parameter a matrix (i.e., transformed proportions matrix).

This is the testing I did with your example dataset in your [vignette](https://rdrr.io/github/Oshlack/speckle/f/vignettes/speckle.Rmd).

```
# Matrix of transformed proportions for the  'exprObj' parameter in dream()
mat <- matrix(props$TransformedProps, ncol = ncol(props$TransformedProps), dimnames = unname(dimnames(props$TransformedProps)))

# Formula for the 'formula' parameter in dream()
form <- ~ group + (1 | pair)

# Sample metadata for the 'data' parameter in dream()
## retrieve data of interest from colData(sce_all)
metadata <- as.data.frame(colData(sce_all))
metadata <- unique(metadata[,c(1,2)])

## create new variable ('pair') which will be included as a random effect 
metadata$pair <- ifelse(metadata$sample%in%c('S1','S2','S3'), '1', '2')

# Fit mixed-effects model with dream()
fit_dream = dream(mat, form, metadata)
fit_dream<- eBayes(fit1)
summary(decideTests(fit_dream))

# Differences between categories
topTable(fit_dream,coef=2)
topTable(fit_dream, coef=3)
topTable(fit_dream, coef=2:3)
```

Thanks!
Aida

**Comment by bphipson** [comment]
Great, thanks Aida!
